plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.80'
    id 'idea'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenLocal()
    maven { url = 'https://maven.neoforged.net/releases' }
    maven { url = 'https://maven.parchmentmc.org' }
    maven { url = 'https://maven.ryanhcode.dev/releases' }
    maven { url = 'https://maven.blamejared.com' }
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly("foundry.veil:veil-neoforge-${minecraft_version}:${veil_version}") {
        exclude group: 'maven.modrinth'
    }
    localRuntime("foundry.veil:veil-neoforge-${minecraft_version}:${veil_version}")

    compileOnly("dev.ryanhcode.sable:sable-neoforge-${minecraft_version}:${sable_version}") {
        exclude group: 'foundry.veil'
    }
    localRuntime("dev.ryanhcode.sable:sable-neoforge-${minecraft_version}:${sable_version}")
}

tasks.withType(ProcessResources).configureEach {
    def replaceProperties = [
            minecraft_version: minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version: neo_version,
            neo_version_range: neo_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: mod_version,
            mod_authors: mod_authors,
            mod_description: mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : mod_name,
                'Implementation-Version'  : project.version,
                'Implementation-Vendor'   : mod_authors
        ])
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}