modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "create_space_integration.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "sable"
type = "required"
versionRange = "[1.2.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ad_astra"
type = "required"
versionRange = "[1.16.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "aeronautics"
type = "optional"
versionRange = "[1.2.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "aeronautics_bundled"
type = "optional"
versionRange = "[1.2.1,)"
ordering = "AFTER"
side = "BOTH"